name: KekikStream Filtreli M3U

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v3

    - name: Python Kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: M3U Listesini Üret
      run: python generate_m3u.py

    - name: Değişiklikleri Repoya Kaydet
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add config.txt rastgele_filmler.m3u
        git commit -m "M3U Listesi ve Config Güncellendi" || exit 0
        git push
